# -*- coding: utf-8 -*-
"""App.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-8Bp03MeV8xFhVhzOyZRB7sJvMB2RsTC
"""

import streamlit as st
import numpy as np
import pickle

# Load the trained logistic regression model
model = pickle.load(open(r"C:\Users\venka\Downloads\logistic_model.pkl", "rb"))

st.title("🚢 Titanic Survival Prediction App")

# User Inputs
pclass = st.selectbox("Passenger Class (Pclass)", [1, 2, 3])
sex = st.selectbox("Sex", ["male", "female"])
age = st.slider("Age", 0, 100, 25)
sibsp = st.number_input("Siblings/Spouses Aboard (SibSp)", min_value=0, max_value=10, value=0)
parch = st.number_input("Parents/Children Aboard (Parch)", min_value=0, max_value=10, value=0)
fare = st.slider("Fare Paid", 0.0, 500.0, 50.0)

# Embarked: C=0, Q=1, S=2
embarked = st.selectbox("Port of Embarkation", ["C", "Q", "S"])
embarked_encoded = {"C": 0, "Q": 1, "S": 2}[embarked]

# Deck: A=0, B=1, C=2, D=3, E=4, F=5, G=6, Unknown=0
deck = st.selectbox("Deck", ["A", "B", "C", "D", "E", "F", "G", "Unknown"])
deck_encoded = {"A": 0, "B": 1, "C": 2, "D": 3, "E": 4, "F": 5, "G": 6, "Unknown": 0}[deck]

# Convert inputs to model format
sex_encoded = 0 if sex == "male" else 1
input_data = np.array([[pclass, sex_encoded, age, sibsp, parch, fare, embarked_encoded, deck_encoded]])

# Predict and Display Result
if st.button("Predict Survival"):
    prediction = model.predict(input_data)
    result = "🎉 Survived!" if prediction[0] == 1 else "💔 Did Not Survive"
    st.subheader(f"Prediction: {result}")

